### PR TITLE
Added timestamps for video 36: Danh Phan: Gaussian Processes

### LINKED ISSUE #59: Add timestamp for video 36 Danh Phan: Gaussian Processes
I will add the timestamp to the video (at this link: https://youtu.be/8YN7dLJlHIE).

### PR DESCRIPTION
**Pull request by HangenYuu**
### Reference
Towards #11 
Closes #59 

### Description
Add timestamps for video 36: Danh Phan: Gaussian Processes

### Event
#DataUmbrellaPyMCSprint

### CODE REVIEW

**Comment by reshamas** [comment]
@HangenYuu This PR is in "draft" mode. Will review once it is out of draft mode.

**Comment by HangenYuu** [comment]
Hi @reshamas the PR is now ready for review.

**Comment by reshamas** [comment]
@HangenYuu Super! Thanks so much! :star: 
The timestamps have been added to the video.

**Comment by HangenYuu** [comment]
Thank you @reshamas for reviewing and merging the PR! As a note, I want to do GSoC 2024 project with PyMC. I will move on to helping with the documentation, small issues, and final proposal in the main repo now.

**Pull request merged**
